apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-giropops
    app: giropops-strigus
  name: nginx-giropops
spec:
  containers:
  - image: nginx
    name: nginx-giropops2
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /giropops
      name: primeiro-volume
    resources:
      requests:
        memory: "400M"
        cpu: "300m"
      limits:
        memory: "600M"
        cpu: "500m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: primeiro-volume
    emptyDir:
      sizeLimit: 256Mi
